In [1]:
import tensorflow as tf
import pandas as pd
from tensorflow.keras.models import load_model
import pickle
import numpy as np

LOAD THE TRAINED MODEL , ALL THE PICKLE FILES (SCALED , ONEHOT ENCODE , LABEL)

In [2]:
model = load_model('model.h5')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [3]:
with open('label_encoder_gender.pkl' , 'rb') as file : 
    label_encoder_gender = pickle.load(file)
 
with open('oneHotEncode_geography.pkl' , 'rb') as file : 
    oneHotEncode_geography = pickle.load(file)

with open('scaler.pkl' , 'rb') as file : 
    scaler = pickle.load(file)

TIME TO PREDICT USING INPUT DATA

In [4]:
input_data = {
    'CreditScore' : 600,
    'Geography' : 'France' ,
    'Gender' : 'Male' ,
    'Age' : 40 ,
    'Tenure' :  3 ,
    'Balance' : 60000 , 
    'NumOfProducts' : 2 , 
    'HasCrCard' : 1 ,
    'IsActiveMember' : 1 ,
    'EstimatedSalary' : 50000,
    
}

In [5]:
## create a data frame for mmy input values 

input_df = pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [6]:
## Geo encode : 

geo_array = oneHotEncode_geography.transform([[input_data['Geography']]]).toarray()
column_names = oneHotEncode_geography.get_feature_names_out(['Geography'])
geo_encoded_df = pd.DataFrame(geo_array , columns =  column_names)
geo_encoded_df

c:\Users\Lenovo\Desktop\AIML\Course-code\2. ANN-Project\.ann-venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [7]:
### now we have to concatenate 
input_df = pd.concat([input_df.drop('Geography' , axis= 1) , geo_encoded_df] , axis =1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [8]:
## NOW WE USE THE LABEL ENCODER TO ENCODE THE GENDER VALUES INTO IT

input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [9]:
input_scaled = scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

<H4 PREDICT CHURN </H4>

<H4> PREDICT CHURN </H4>

In [10]:
prediction = model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 395ms/step

array([[0.02258843]], dtype=float32)